site/components/PSNavigation.tsx
site/package-lock.json
site/package.json
site/src/app/layout.tsx
site/src/app/v2/accueil/page.tsx

feat(site): add navigation

---

site/components/PSBreadcrumb/PSBreadcrumb.tsx
site/src/app/layout.tsx
site/src/app/page.tsx

Permet de charger la home page sur `/v2/accueil` également sur `/`

fix(site): add home page to default / route

---

site/package-lock.json
site/package.json

⬆️ 
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=7c51b26327ff4099bed6d63d52c96772&p=1f89830a2fca4deea5ecfd189e638bdc&pm=s

[Frontend] upgraded react-dsfr from 1.7.2 to 1.9.8

---

site/src/app/v2/trouver-un-club/page.tsx
site/src/app/v2/trouver-un-club/style.module.scss

contenu:
- ajout du panel
- pas de peaufinage en version mobile car il y a un ticket spécifique pour cette page

feat/ information panel on page to search club

---

.github/workflows/site-test.yml
site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumb.tsx
site/src/app/v2/une-question/agent.ts

- fix TS issue
- comment accessibility for now

hotfix(site): fix type issue that prevent prod deployment

---

.github/workflows/site-test.yml
site/pages/api/contact.ts
site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumb.tsx
site/src/app/v2/une-question/agent.ts
site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx
site/utils/crisp.ts

- Typing fixes and refactoring (CRISP_WEBSITE also added to the env schema validation/parsing)
- Re-enabled accessibility test runs

[Backend][Frontend][CI] Build fixes with typing fixes + various improvements

---

site/src/app/v2/une-question/agent.ts
site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx

@Destinyyyy Y'a eu une petite erreur introduite pendant le refacto sur les types qui casse le formulaire de contact donc je remets l'ancien code

fix(site): send form and not state of the form

---

data/cleaned_to_email_campaign_csv.ipynb
data/cleaned_to_email_campaign_csv.py

- Nom et prénom en minuscules
- Séparation en 2 csv distincts pour les 2 templates de mail

fix(data): only keep may column, capitalize, seperate csvs

---

site/src/app/v2/accueil/components/social-media-panel/SocialMediaPanel.tsx
site/src/app/v2/une-question/page.tsx

- Social links banner, horizontal padding added
- Contact form on FAQ page, horizontal padding added

[Frontend] Tiny modifications for mobile support

---

.gitignore
site/src/app/v2/test-eligibilite/components/socialMediaLinks/SocialMediaLinks.tsx

⬆️ 
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=ac4ce8d2a8704200921ae3f57d382368&pm=s

[Frontend] Social links in the eligibility flow should open in a new tab

---

.github/workflows/site-test.yml
.gitignore
site/.eslintrc.json
site/components/PageHeader/styles.module.scss
site/package-lock.json
site/package.json
site/pages/api/contact.ts
site/src/app/components/pass-sport-footer/PassSportFooter.tsx
site/src/app/components/pass-sport-navigation/PassSportNavigation.tsx
site/src/app/globals.scss
site/src/app/utilities.module.scss
site/src/app/v2/accueil/components/PresentationTile.tsx
site/src/app/v2/accueil/components/find-club-card/FindClubCard.tsx
site/src/app/v2/une-question/client-agent.ts
site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx
site/src/app/v2/une-question/components/ContactForm/styles.module.scss
site/src/app/v2/une-question/components/ContactSection/ContactSection.tsx
site/src/app/v2/une-question/components/ContentSection/ContentSection.tsx
site/src/app/v2/une-question/components/ContentSection/styles.module.scss
site/src/app/v2/une-question/components/PopularityLevel/PopularityLevel.tsx
site/src/app/v2/une-question/components/PopularityLevel/styles.module.scss
site/src/app/v2/une-question/page.tsx
site/src/app/v2/une-question/server-agent.ts
site/src/app/v2/une-question/styles.module.scss
site/types/Crisp.ts
site/types/Faq.ts
site/utils/faq.ts

- Implementation of mobile support
- API calls to Crisp API to get categories and their categories (two calls are necessary to construct the object for the frontend to work with, call to get categories, and call to get articles, and then some mapping)
- Contact form modal implemented
- No search bar as this is currently blocked (need more information as an article cannot belong to several categories so this does not work with the current UI)
- Various refactoring
- Added eslint plugin to get rid of unecessary curly braces when putting a string into a property
- Example: `<Component props={"test"}/>` has to become `<Component props="test"/>`
- Added lib "react-markdown" in order to display article's content retrieved from CRISP + a remark plugin to support line breaks
- Added …

[Frontend][Backend] FAQ full rework

---

site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx
site/src/app/v2/une-question/components/ContactSection/ContactSection.tsx

- Removed leftover console.log
- "Acceder a la faq" becomes "Lire la FAQ", and it simply closes the modal

[Frontend] Contact form modal updated

---

site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx

⬆️ 
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=8ba66bdc3cc84d8fa6aeb8cab2065305&pm=s

[Frontend] Remove "copy by email" block temporarily

---

site/utils/faq.ts

[Backend] FAQ cache fix (cache each article by key)

---

site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx

⬆️ 
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=60015b901ff5435b979a4760f7d75c86&pm=s

[Frontend] Contact form, success notification text update

---

site/src/app/components/pass-sport-footer/PassSportFooter.tsx

- Qu'est-ce que le pass Sport => Tout savoir sur le pass Sport
- Trouver un club partenaire => Trouver une structure partenaire
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=44743b759004425e9ad0a780710c33ca&pm=s

[Frontend] Footer links text update 

---

site/components/PageHeader/PageHeader.tsx
site/src/app/components/pass-sport-breadcrumb/PassSportBreadCrumb.tsx
site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumbPro.tsx
site/src/app/components/pass-sport-navigation/PassSportNavigation.tsx
site/src/app/components/pass-sport-navigation/navigation.tsx
site/src/app/hooks/use-get-clubs.tsx
site/src/app/hooks/use-is-pro-version.tsx
site/src/app/v2/pro/accueil/page.tsx
site/src/app/v2/pro/trouver-un-club/[club-name]/page.tsx
site/src/app/v2/pro/trouver-un-club/page.tsx
site/src/app/v2/pro/trouver-un-club/styles.module.scss
site/src/app/v2/trouver-un-club/[club-name]/components/clubDetails/ClubDetails.tsx
site/src/app/v2/trouver-un-club/[club-name]/layout.tsx
site/src/app/v2/trouver-un-club/[club-name]/page.tsx
site/src/app/v2/trouver-un-club/components/club-filters/ClubFilters.tsx
site/src/app/v2/trouver-un-club/components/club-filters/styles.module.scss
site/src/app/v2/trouver-un-club/components/club-finder/ClubFinder.tsx
site/src/app/v2/trouver-un-club/page.tsx

- Find a club support for pro version
- Refactored some of the components in order to be used in a shared layout (added hooks etc.)
- Removed border radius from club filters
- Removed " - Code postal" from filter label

[Frontend] Trouver un club pro version

---

site/src/app/v2/pro/accueil/page.tsx

⬆️ 
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=611893844d3345acbe634cbd92100b38&pm=s

[Frontend] Home page pro typo update

---

site/src/app/components/pass-sport-footer/PassSportFooter.tsx

⬆️ 
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=d301326c7de74c4ab96561c920c396a4&pm=s

[Frontend] Footer links support for user/pro version

---

site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumbStandard.tsx
site/src/app/components/pass-sport-breadcrumb/styles.module.scss

[Frontend] Remove breadcrumb from code page

---

site/src/app/v2/une-question/components/ContentSection/ContentSection.tsx

⬆️ 
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=d4d913a431224ba097cdb25d30813f89&pm=s

[Frontend] FAQ - Track category + article click

---

site/src/app/v2/pro/une-question/page.tsx

Background color of the social link panel contained the wrong color

[Frontend] FAQ Pro version - Social panel background

---

site/src/app/v2/une-question/components/ContentSection/ContentSection.tsx
site/types/Crisp.ts
site/types/Faq.ts
site/utils/faq.ts

- In the list of articles, only display the title
- Don't display articles whose visibility is "hidden"
- Sort categories & articles (from 1 to x)
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=747e69832ca54145a05a0807b72e46cf&pm=s

[Frontend] FAQ - Various updates

---

site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumbPro.tsx
site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumbStandard.tsx
site/src/app/components/pass-sport-footer/PassSportFooter.tsx
site/src/app/v2/plan-du-site/page.tsx
site/src/app/v2/plan-du-site/style.module.scss
site/src/app/v2/pro/plan-du-site/page.tsx
site/src/app/v2/pro/plan-du-site/style.module.scss

⬆️ 
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=33ce34d6f6064fa89dafc9d76ea1515e&pm=s

[Frontend] Plan du site - user & pro

---

site/README.md
site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/page.tsx

⬆️ 
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=7cdd658c46764d79b6bab029bafe7745&pm=s

[Frontend] pass Sport wordings

---

site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/page.tsx
site/src/app/v2/pro/trouver-un-club/[club-name]/page.tsx
site/src/app/v2/pro/trouver-un-club/page.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/components/about.tsx
site/src/app/v2/trouver-un-club/[club-name]/page.tsx

[Frontend] Wordings update (pass Sport)

---

site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumbStandard.tsx
site/src/app/components/pass-sport-footer/PassSportFooter.tsx
site/src/app/components/pass-sport-navigation/navigation.tsx
site/src/app/v2/accueil/components/find-club-card/FindClubCard.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/components/how-to-use-pass-sport.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/styles.module.scss
site/src/app/v2/trouver-un-club/[club-name]/components/clubDetails/ClubDetails.tsx

- In club details, update "activités" wording to be singular when there is only one activity
- QR code image updated in "Tout savoir sur le pass Sport" user page, aspect ratio also set to 1 / 1 for better display
- Updated "Trouver une structure partenaire" to "Trouver un club partenaire" for user version
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=2e314f9def7b464ab30c8b8bba2a5441&pm=s
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=6ce2cd51a68f4b20a456f1cb00497087&pm=s
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=d7c69eb6af174fbf8d93d7d3d8fde428&pm=s

[Frontend] Various UI fixes + wording updates

---

site/src/app/v2/plan-du-site/page.tsx
site/src/app/v2/pro/plan-du-site/page.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/components/how-to-use-pass-sport.tsx

⬆️ 
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=33ce34d6f6064fa89dafc9d76ea1515e&pm=s
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=6ce2cd51a68f4b20a456f1cb00497087&pm=s

[Frontend] Wordings update

---

site/src/app/v2/test-eligibilite/components/qrcode-verdict/QrCOdeVerdict.tsx
site/src/app/v2/test-eligibilite/components/qrcode-verdict/styles.module.scss

https://www.notion.so/En-tant-que-b-n-ficiaire-je-souhaite-t-l-charger-un-PDF-la-fin-du-test-d-obtention-du-code-Pass-S-8cd88c392782415aa3b169b8146a4d77?pvs=4

feat / enable pdf download after eligibility test for june

---

proxy-prod/servers.conf.erb

/obtenir-mon-code/ => https://pass.sports.gouv.fr/v2/test-eligibilite
/structures-daccueil/ => https://pass.sports.gouv.fr/v2/trouver-un-club
/faq/passsport-quest-ce-que-cest/  => https://pass.sports.gouv.fr/v2/une-question;

[Nginx] Added 3 more redirections

---

site/src/app/v2/trouver-un-club/components/club-filters/ClubFilters.tsx

UI fixes on find-a-club inputs, also support for responsive
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=e8691bf4439641ffa5acf93144aaf0a1&pm=s

[Frontend] Ui fixes on find a club inputs

---

site/src/app/components/pass-sport-footer/PassSportFooter.tsx

The logo is now redirecting to https://www.helloasso.com/secteurs/clubs-sportifs
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=be8e6f5b12744ca3ad4e6dd1c37323c7&pm=s

[Frontend] Updated Hello Asso link in footer

---

site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/components/TranscriptionVisibilityClub.tsx
site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/components/Video.tsx
site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/components/styles.module.scss
site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/page.tsx

Updated content & Added one video (the other video is missing so, not adding it for now)
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=84e31f26ccdd4a42b0fda53560c507ee&pm=s

[Frontend] Pro version - Tout savoir sur le pass sport page updated

---

site/src/app/v2/trouver-un-club/components/club-filters/ClubFilters.tsx
site/src/app/v2/trouver-un-club/components/club-filters/region-filter/RegionFilter.tsx

- Possibilité d'avoir un query param sur l'URL des clubs pour filtrer

feat(site): add region query param url filter

---

site/src/app/v2/mentions-legales/page.tsx

- Mentions legales updates
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=eabdb3ae84194f0a83df30225aad1e1e&pm=s

[Frontend] Mentions legales updated

---

site/src/app/v2/politique-de-confidentialite/page.tsx

- Politique de confidentialite page updated
- Vimeo section updated as well as it was only taking into consideration the video from the homepage (there are other viemo videos on the tout savoir sur le pass sport page pro version)
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=ee6dce42a579474ca9997ede424a18b5&pm=s

[Frontend] Politique de confidentialite update

---

site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumbStandard.tsx
site/src/app/components/pass-sport-footer/PassSportFooter.tsx
site/src/app/v2/reglement-du-jeu-concours-numero-1-pass-sport/page.tsx
site/src/app/v2/reglement-du-jeu-concours-numero-1-pass-sport/style.module.scss

⬆️ 
https://www.notion.so/En-tant-que-visiteur-je-souhaite-acc-der-au-jeu-concours-035f9a82de824b039e0ae5018926ce8a

[Frontend] Implementation of page concours 1

---

site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/page.tsx

Aso -> Asso
And removed dead link

[Frontend] Tout savoir sur le pass sport pro version wordings update

---

site/src/app/v2/test-eligibilite/components/allowance-step/AllowanceStep.tsx

Updated introduction wording in eligbility funnel
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=74ef8662349d4840926dbd8b0dddcb4d&pm=s

[Frontend] Eligibility test - Wording update

---

site/src/app/v2/code/scan/[...rest]/page.tsx
site/src/app/v2/code/scan/[encrypted]/components/QrCodeCard/QrCodeCard.tsx

- Added catch all route to intercept query parameters with slahes non encoded
- Pushed event when printing the QR code on the recap page

[Frontend] QR Code fixes

---

site/src/app/v2/reglement-du-jeu-concours-numero-1-pass-sport/page.tsx

⬆️ 
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=d1fc8c7fbff44bc6a0492bc70bef0276&pm=s

[Frontend] jeu-concours 1 content updated

---

site/src/app/constants/search-query-params.ts
site/src/app/v2/pro/trouver-un-club/page.tsx
site/src/app/v2/test-eligibilite/components/city-finder/CityFinder.tsx
site/src/app/v2/trouver-un-club/agent.ts
site/src/app/v2/trouver-un-club/components/club-filters/ClubFilters.tsx
site/src/app/v2/trouver-un-club/components/club-filters/city-filter/CityFilter.tsx
site/src/app/v2/trouver-un-club/components/club-filters/department-filter/DepartmentFilter.tsx
site/src/app/v2/trouver-un-club/components/club-filters/styles.module.scss
site/src/app/v2/trouver-un-club/components/club-finder/ClubFinder.tsx
site/src/app/v2/trouver-un-club/page.tsx
site/types/Department.ts

- Added departmentFilter and retain it in URL
- Added escaped single quotes for city filter
- Added UI fixes
When selection a region, the departments available are the ones that have the same regionCode.
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=f00105906f624b98b13364e4a9e87352&pm=s

[Frontend] Find a club - added departmentFilter

---

site/src/app/Matomo.tsx

Use of pathName from usePathname() instead of window.location
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=f372de3c869d420889a998d652114d70&pm=s

[Frontend] Matomo another attempt

---

site/src/app/Matomo.tsx

Revert latest matomo update (build broken)

[Fonrtend] Revert "chore: matomo another attempt"

---

site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumbStandard.tsx
site/src/app/v2/test-eligibilite/page.tsx

⬆️ 
Confirm with Perrine & Rayhane

[Frontend] Removed breadcrumb from eligibility test page

---

site/src/app/v2/test-eligibilite/components/city-finder/CityFinder.tsx

[Frontend] City finder eligiblity test revert

---

site/src/app/v2/test-eligibilite/components/allowance-step/AllowanceStep.tsx
site/src/app/v2/test-eligibilite/components/city-finder/CityFinder.tsx
site/src/app/v2/test-eligibilite/components/city-finder/styles.module.scss
site/src/app/v2/test-eligibilite/components/custom-input/CustomInput.tsx
site/src/app/v2/test-eligibilite/components/step-one-form/StepOneForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/YoungCafForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/YoungMsaForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/common-msa-inputs/CommonMsaInputs.tsx

⬆️ 
- https://www.notion.so/Page-form-ligibilit-pr-ciser-le-format-des-champs-nom-b-n-f-pr-nom-b-n-f-nom-alloc-pr-nom-all-4336b9d52744451a96465e9a2eeba82b
- https://www.notion.so/Page-form-ligibilit-modifier-texte-champ-commune-de-r-sidence-alloc-1403826cc0cb48e7bfde53da41f69bf8
- https://www.notion.so/Accessibilit-formulaire-Code-Remonter-une-phrase-avant-la-premi-re-question-du-formulaire-c27dfdde426c42dd8155295f75210675
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=886e26dd4af44b0c9fd1176137d79aa9&pm=s

[Frontend] Eligibility form wordings update + city finder label functionality added

---

site/src/app/v2/test-eligibilite/components/eligibility-test-forms/EligibilityTestForms.tsx
site/src/app/v2/test-eligibilite/components/step-one-form/StepOneForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/AahCafForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/AahMsaForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/YoungCafForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/YoungMsaForm.tsx

When completing the eligibility test, track the success/failure
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=2e1e7ac2feed462fb9f8701635966e4d&pm=s

[Frontend] Matomo - Eligibility test event tracking (success & failure)

---

.github/workflows/assign-author.yml

Auto assign PR to author
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=d2733bd4eee6487ab57040e63924f46c&pm=s

[CI] Auto assign author

---

site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/page.tsx
site/src/app/v2/reglement-du-jeu-concours-numero-1-pass-sport/page.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/components/legal-text-reference.tsx
site/src/app/v2/trouver-un-club/components/club-finder/ClubFinder.tsx

[Frontend] Decret updated on tout savoir sur le pass Sport (user & pro version)

---

site/src/app/v2/test-eligibilite/components/step-one-form/StepOneForm.tsx

Typo fix
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=4b09ad1bdab04ccaa1f5424562c6c45e&pm=s

[Frontend] Beneficaire wording fix

---

site/src/app/v2/trouver-un-club/[club-name]/components/clubDetails/ClubDetails.tsx
site/types/Club.ts

Type checking on "activities" field, it can be null according to ODS's catalog
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=fa80428c78634873b93a8cb39db584df&pm=s

[Frontend] Bug fix app crash on club details page

---

site/instrumentation.ts

Reduce sample rate to not congest the sentry shared instance
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=eb9eadc74c8e4e79adc1e1e7b758af1e&pm=s

[CI] Sentry - sampleRate reduced from 1 to 0.1

---

site/src/app/v2/code/scan/[encrypted]/components/QrCodeCard/QrCodeCard.tsx
site/src/app/v2/code/scan/[encrypted]/page.tsx
site/src/app/v2/code/scan/[encrypted]/styles.module.scss

- page's title updated
- tag main added for skip link
- heading level updated
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=5c9fdad4422a41f2b1b3188177b403e9&pm=s

[Frontend] Accessibility - QR Code recap page

---

site/components/eligibility-test-banner/EligibilityTestBanner.tsx
site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/components/TranscriptionVisibilityClub.tsx
site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/page.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/components/about.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/components/how-to-use-pass-sport.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/components/obtain-pass-sport.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/components/where-to-use-pass-sport.tsx

- Accessibility tweaks for both version pro and user
- Removed completely <br/>, using span and css classes instead
- Replaced buttons with links (including in the shared component EligibilityTestBanner)
- Le compte asso button did nothing, added a link to it with href
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=5c9fdad4422a41f2b1b3188177b403e9&pm=s

[Frontend] Accessibility - Tout savoir sur le pass Sport pro/user version

---

site/src/app/v2/mentions-legales/page.tsx

- replaced <br/> with <span>
- Added Link mailto for email
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=3e4ddcce8ea94d509d90174f762f81dc&pm=s

[Frontend] Accessibility - Mention legales

---

site/src/app/components/mission-cards/MissionCards.tsx
site/src/app/components/verdictPanel/VerdictPanel.tsx
site/src/app/v2/test-eligibilite/components/allowance-step/AllowanceStep.tsx

- Tweaked heading levels to be in conformity with accessibility rules
- Moved role="status" from fieldset to div to be valid
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=001d45432b354ae2887c80841fc52f76&pm=s

[Frontend] Accessibility - Eligibility form missing accessibility stuff

---

site/src/app/components/pass-sport-navigation/PassSportNavigationPro.tsx
site/src/app/utilities.module.scss
site/src/app/v2/accueil/page.tsx
site/src/app/v2/code/scan/[encrypted]/page.tsx
site/src/app/v2/mentions-legales/page.tsx
site/src/app/v2/plan-du-site/page.tsx
site/src/app/v2/politique-de-confidentialite/page.tsx
site/src/app/v2/pro/accueil/page.tsx
site/src/app/v2/pro/plan-du-site/page.tsx
site/src/app/v2/pro/ressources/page.tsx
site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/page.tsx
site/src/app/v2/pro/trouver-un-club/page.tsx
site/src/app/v2/pro/une-question/page.tsx
site/src/app/v2/reglement-du-jeu-concours-numero-1-pass-sport/page.tsx
site/src/app/v2/reglement-du-jeu-concours-numero-2-pass-sport/page.tsx
site/src/app/v2/test-eligibilite/page.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/page.tsx
site/src/app/v2/trouver-un-club/page.tsx
site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx
site/src/app/v2/une-question/components/ContactForm/styles.module.scss
site/src/app/v2/une-question/components/ContactSection/ContactSection.tsx
site/src/app/v2/une-question/components/ContentSection/ContentSection.tsx
site/src/app/v2/une-question/components/ContentSection/styles.module.scss
site/src/app/v2/une-question/components/QuestionAnswer/QuestionAnswer.tsx
site/src/app/v2/une-question/page.tsx

- Accessibility implementation on FAQ page
- Contact modal form
- Page of FAQ when list of articles are expanded
- Page of FAQ when list of articles are collapsed
- Now the page is fully navigable with the keyboard (tabulation, enter keys, etc.)
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=3e4ddcce8ea94d509d90174f762f81dc&pm=s

[Frontend] FAQ - Accessibility

---

site/src/app/components/social-media-panel/SocialMediaPanel.tsx
site/src/app/layout.tsx
site/src/app/v2/accueil/components/PresentationTile.tsx
site/src/app/v2/accueil/components/callout/Callout.tsx
site/src/app/v2/accueil/components/find-club-card/FindClubCard.tsx
site/src/app/v2/accueil/components/hero-panel/HeroPanel.tsx
site/src/app/v2/accueil/components/video/Video.tsx
site/src/app/v2/accueil/page.messages.tsx
site/src/app/v2/pro/accueil/components/PresentationTile.tsx
site/src/app/v2/pro/accueil/page.tsx
site/src/app/v2/pro/accueil/styles.module.scss

- Homepage accessibility
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=2d2761c3e2a244b0b52a62dd9090200f&pm=s

[Frontend] Accessibility - Homepage user/pro

---

site/src/app/v2/accueil/components/video/Video.tsx

[Frontend] Perrine various feedbacks

---

site/src/app/v2/reglement-du-jeu-concours-numero-1-pass-sport/page.tsx
site/src/app/v2/reglement-du-jeu-concours-numero-2-pass-sport/page.tsx

⬆️ 
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=30611bbfc29448b1b9c3bd88a62c1efb&pm=s

[Frontend] Accessibility - Concours pages

---

site/src/app/v2/plan-du-site/page.tsx
site/src/app/v2/pro/plan-du-site/page.tsx

⬆️ 
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=a8e082364add4cf29ad22f537d56d6ec&pm=s

[Frontend] Accessibility - Plan du site

---

site/components/PageHeader/PageHeader.tsx
site/src/app/components/social-media-panel/SocialMediaPanel.tsx
site/src/app/components/social-media-panel/styles.module.scss
site/src/app/v2/accueil/components/PresentationTile.tsx
site/src/app/v2/accueil/components/hero-panel/HeroPanel.tsx
site/src/app/v2/pro/accueil/components/PresentationTile.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/components/how-to-use-pass-sport.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/components/legal-text-reference.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/components/obtain-pass-sport.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/components/where-to-use-pass-sport.tsx

Perrine feedback on accessibility

[Frontend] Perrine feedback part 2

---

site/src/app/components/mission-cards/MissionCards.tsx
site/src/app/v2/test-eligibilite-mai/components/Question/Question.tsx
site/src/app/v2/test-eligibilite/components/allowance-step/AllowanceStep.tsx
site/src/app/v2/test-eligibilite/components/city-finder/CityFinder.tsx
site/src/app/v2/test-eligibilite/components/qrcode-verdict/QrCOdeVerdict.tsx
site/src/app/v2/test-eligibilite/components/step-one-form/StepOneForm.tsx
site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx
site/tsconfig.json

- Improved forms UX by focusing on the first invalid input after submitting the form
- Fixed MissionCard to be accessible (p elements contained p children)
- Deletion of wording associated to email input in the eligibility form
- Tweaked eligibility form accessibility to properly announce block elements with the role "alert"
PS: Some code repetition code can be seen, it is due to the fact that states are structured differently in both forms
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=65e423cf7415482a85fc8d5548a496d3&pm=s
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=980890af1d41453bbeb472c4cb191dfe&pm=s

[Frontend] Forms UX improvements + accessibility tweaks on eligibility form

---

proxy-prod/servers.conf.erb

[Backend] Redirection to homepage from /le-passsport-reconduit-pour-la-saison-2023-2024

---

site/src/app/v2/pro/ressources/components/about.tsx
site/src/app/v2/pro/ressources/page.tsx
site/src/app/v2/pro/ressources/styles.module.scss

⬆️ 
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=344d6513b0eb49d08bd76827d2d84598&pm=s

[Frontend] Accessibility - Ressources page pro

---

site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/page.tsx
site/src/app/v2/pro/trouver-un-club/page.tsx
site/src/app/v2/trouver-un-club/components/club-finder/ClubFinder.tsx
site/src/app/v2/trouver-un-club/components/missing-club-information-panel/MissingClubInformationPanel.tsx

[ticket](https://www.notion.so/Site-partenaire-Carte-des-structures-partenaires-modification-texte-b07774dd0abe4721ae69becf07594fbb?pvs=4)

update words, update information panel when clubs are missing on pro page

---

site/src/app/v2/mentions-legales/page.tsx
site/src/app/v2/politique-de-confidentialite/page.tsx

[Frontend] Page politique de confidentialite UI Fix (due to page header refactoring)

---

site/src/app/components/custom-highlight/CustomHighlight.tsx
site/src/app/components/custom-highlight/styles.module.scss
site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/page.tsx
site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/styles.module.scss
site/src/app/v2/tout-savoir-sur-le-pass-sport/components/about.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/styles.module.scss

- Updated content on page "Tout savoir sur le pass Sport" pro version
- Created custom components that are being reused in multiple places "CustomHighlight" (Highlight with icon)
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=1d773752ca3945b1bbdef11ce15df6cd&pm=s

[Frontend] Tout savoir sur le pass Sport updates - pro version 

---

data/2024/2_merge_with_existing.ipynb

Do not take benef that have column a_valider set to true, it means they were added manually. If we take them, it will cause a conflict upon inserting them in the database

[Backend] Blacklist benef that have a_valider to true

---

site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/components/Video.tsx

The cookies on tout savoir sur le pass sport page pro version were deposited before consent because src from iframe was set
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=e7ec746cde904d5b9329e0c1e346af66&pm=s

[Frontend] Remove src from iframe before cookie consent

---

site/src/app/v2/reglement-du-jeu-concours-numero-1-pass-sport/page.tsx
site/src/app/v2/reglement-du-jeu-concours-numero-2-pass-sport/page.tsx

⬆️ 
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=8d3f5038992f49dc90440353675654eb&pm=s

[Frontend] Concours pages UI regression fixes

---

site/src/app/v2/trouver-un-club/[club-name]/components/clubDetails/ClubDetails.tsx
site/src/app/v2/trouver-un-club/[club-name]/components/map/Map.tsx

⬆️ 
- https://www.notion.so/Page-Trouver-un-club-partenaire-certaines-structures-n-ont-pas-d-adresse-pas-de-coordonn-es-et-pa-a81c409cccb54d5ba8cf2651980f5ef4
- https://www.notion.so/Page-d-tails-club-partenaire-si-coordonn-es-strcuture-non-pr-sents-afficher-un-message-qui-expliq-1901b8e3d17a46b2b0d02c6e7fced91f
https://pass-sport-staging-pr251.osc-secnum-fr1.scalingo.io/v2/trouver-un-club/BOUGIVAL%20FOOTBALL
https://pass-sport-staging-pr251.osc-secnum-fr1.scalingo.io/v2/trouver-un-club/AILES%20SPORTIVES%20AIRBUS%20HELICOPTERS
https://pass-sport-staging-pr251.osc-secnum-fr1.scalingo.io/v2/trouver-un-club/COMITE%20DEPARTEMENTAL%20DE%20LA%20FEDERATION%20FRANCAISE%20DE%20LA%20MONTAGNE%20ET%20DE%20L%20ESCALADE%20DES%20ALPES%20DE%20HAUTE%20PROVENCE …

[Frontend] Club details- Missing info placeholder

---

site/src/app/v2/pro/accueil/page.tsx

[ticket](https://www.notion.so/l-accessible-name-de-l-image-n-est-pas-suffisamment-descriptif-du-contenu-visible-dans-l-image-d5d8582f5fbb4a178aef1995d0c8305a?pvs=4)

set empty alt for images

---

site/src/app/v2/code/scan/[encrypted]/page.tsx
site/src/app/v2/code/scan/components/MainContent/MainContent.tsx
site/src/app/v2/code/scan/components/ProContent/ProContent.tsx

- Updated LCA redirection URL (removed query parameter that used to contain the code)

[Frontend] QR Page - Update LCA button redirection to login page

---

site/jest.config.js
site/pages/api/contact.ts
site/src/app/v2/pro/une-question/page.tsx
site/src/app/v2/une-question/client-agent.ts
site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx
site/src/app/v2/une-question/components/ContactSection/ContactSection.tsx
site/types/Contact.ts

[ticket](https://www.notion.so/Retravailler-les-segments-envoy-s-CRISP-objets-structures-fed4e5a7cdea4e6797b0d5ad25a8d197?pvs=4)
[ticket](https://www.notion.so/Retravailler-les-segments-envoy-CRISP-pour-les-demandes-de-support-objets-particuliers-179b75b18a234faba80c3b2ed5e7bdd9?pvs=4)

feat / update crisp segments

---

site/src/app/v2/code/scan/components/ProContent/ProContent.tsx

[Frontend] LCA Redirection text update

---

site/src/app/v2/code/scan/components/ProContent/ProContent.tsx

[Frontend] LCA redirection text update suggestion

---

site/src/app/components/pass-sport-footer/styles.module.scss

[Frontend] Intersport logo height updated

---

site/src/app/v2/pro/trouver-un-club/page.tsx

⬆️ 
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=02d2238e637c4d3ab6f5992111be6e4d&pm=s

[Frontend] Pro carto - Update typo years

---

site/src/app/v2/test-eligibilite/components/crous-step/CrousStep.tsx

⬆️ 
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=012ea54cde57464391078caf510fcb69&pm=s

[Frontend] Boursier form wordings update

---

site/src/app/v2/politique-de-confidentialite/page.tsx

🆙 
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=fe17cf94ea164f368f3340d73e9eec33&pm=s

[Frontend] Politique de confidentialité update

---

site/pages/api/contact.ts

[Backend] Only add tentative-code segment when needed

---

site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx

⬆️ 
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=5cc9d584115b43ddad288c100991f133&pm=s

[Frontend] FAQ - Modal typo updates

---

site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx

[Frontend] Contact form - visitor new object/segment

---

site/pages/api/contact.ts
site/src/app/v2/une-question/client-agent.ts
site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx
site/types/Contact.ts

- [ticket](https://www.notion.so/Formulaire-de-contact-Ajouter-un-champ-RNA-optionnel-sur-le-formulaire-de-contact-structure-pro-ff77b22614064f3db0c0ab5ee7e88013?pvs=4)
- [reviewapp](https://pass-sport-staging-pr283.osc-secnum-fr1.scalingo.io/)

feat/ add rna field in contact form

---

site/src/app/v2/trouver-un-club/agent.ts

Added try catches for api calls on trouver un club page
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=529ca5aa28984ff8a0fa8da24f7a1c03&pm=s

[Frontend-Backend] Crash handling third party API

---

site/src/app/v2/tout-savoir-sur-le-pass-sport/components/how-to-use-pass-sport.tsx

⬆️ 
- https://www.notion.so/Double-alternative-textuelle-f2572c2d2b1e4291b5aac3eeef5fd02b?d=104d86210f7a80e6b4b7001c15879937

[Frontend] Tout savoir sur le pass Sport - aria-label removed from QR code

---

site/src/app/v2/trouver-un-club/components/clubs-map/Clusterizer.tsx

[ticket](https://www.notion.so/Marqueurs-de-la-carte-1d0a5df73112459099935cb3d79d0e81?pvs=4)

use alt instead of title to set accessible name

---

site/src/app/v2/trouver-un-club/agent.ts
site/src/app/v2/trouver-un-club/components/club-finder/ClubFinder.tsx
site/src/app/v2/trouver-un-club/components/club-list-view/ClubListView.tsx
site/src/app/v2/trouver-un-club/components/club-list-view/more-clubs-button/MoreClubsButton.tsx
site/src/app/v2/trouver-un-club/components/club-list-view/more-clubs-button/styles.module.scss
site/src/app/v2/trouver-un-club/components/club-list-view/styles.module.scss
site/src/app/v2/trouver-un-club/components/club-map-view/ClubMapView.tsx
site/utils/club-finder.ts
site/utils/map.ts

[ticket](https://www.notion.so/R-sultat-de-la-liste-1fee5fef1bbc4b1a8adc3f3d3401d96a?pvs=4)

[accessibility] display clubs count in the button label

---

site/src/app/v2/mentions-legales/page.tsx

Duplicate from https://github.com/betagouv/pass-sport/pull/318
- https://www.notion.so/Audit-avec-tickets-notion-526ecd6d84764c0c84844c2e41071fe2?p=244218ac98674885923b9ee5f12331d4&pm=s

[Accessibility] add contact form for accessibility to legal page

---

site/src/app/hooks/accessibility/use-enhance-cookie-manager-accessibility.ts

- Duplicated dialog removed
- Button containing info when clicked upon was removed
- The info from the button is moved below each service description with proper attributes role heading + aria-level
- https://www.notion.so/Audit-avec-tickets-notion-526ecd6d84764c0c84844c2e41071fe2?p=fede5d6d662849379b84f6ef0ab4111f&pm=s
- https://www.notion.so/Audit-avec-tickets-notion-526ecd6d84764c0c84844c2e41071fe2?p=0ffd86210f7a808699cedc8ef0a8b4e9&pm=s

[Tarteaucitron] Dialog duplicate removed + button info removed + info content moved

---

site/src/app/v2/api/eligibility-test/confirm/route.ts

⬆️  Accept Jeune and jeune, and always send "jeune" to LCA

[Backend] Permissive situation jeune eligibility form

---

site/src/app/components/pass-sport-footer/PassSportFooter.tsx
site/src/app/components/pass-sport-navigation/PassSportNavigationPro.tsx
site/src/app/components/pass-sport-navigation/PassSportNavigationStandard.tsx
site/src/app/components/pass-sport-navigation/navigation.tsx
site/src/app/v2/accueil/components/hero-panel/HeroPanel.tsx

there is no ticket. This is from a comment below the accessibility board

[accessibility] remove useless aria-labels

---

site/src/app/v2/test-eligibilite/components/step-one-form/StepOneForm.tsx
site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx

there is no ticket. See comment below the accessibility board

[Accessibility] fix autocomplete

---

site/package-lock.json
site/package.json
site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx

- Contact form corrections
- Updated @codegouv/react-dsfr version to include changes related to accessibility
- https://github.com/codegouvfr/react-dsfr/releases/tag/v1.13.6
- https://www.notion.so/Audit-avec-tickets-notion-526ecd6d84764c0c84844c2e41071fe2?p=89cd7f76b2854e49b011c4341ea76afd&pm=s

[Accessibility] Contact modal form accessibility corrections

---

site/src/app/v2/test-eligibilite-base/components/aeehStep/AeehStep.tsx
site/src/app/v2/test-eligibilite-base/components/ageStep/AgeStep.tsx
site/src/app/v2/test-eligibilite-base/components/ageStep2/AgeStep2.tsx
site/src/app/v2/test-eligibilite-base/components/allowancesStep/AllowancesStep.tsx
site/src/app/v2/test-eligibilite-base/components/childAgeStep/ChildAgeStep.tsx
site/src/app/v2/test-eligibilite-base/components/customRadioButtons/CustomRadioButtons.tsx
site/src/app/v2/test-eligibilite-base/components/customRadioButtons/styles.module.scss
site/src/app/v2/test-eligibilite-base/components/forWhoStep/ForWhoStep.tsx
site/src/app/v2/test-eligibilite/components/allowance-step/AllowanceStep.tsx
site/src/app/v2/test-eligibilite/components/crous-step/CrousStep.tsx

[ticket](https://www.notion.so/Affichage-des-formulaires-fed16d270e194281b589cbfcad2c47ef?pvs=4)

[Accessibility] add button below radio button fieldsets

---

site/src/app/v2/test-eligibilite/components/step-one-form/StepOneForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/AahCafForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/YoungCafForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/YoungMsaForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/common-msa-inputs/CommonMsaInputs.tsx

🆙 
- https://www.notion.so/Formulaire-Lang-champ-date-de-naissance-combobox-9319156ab32b40138dc27d3752dd0add?pvs=4#cf4fec8a0bc24847a548c04bf7c0347a

[Frontend] Eligibility form - Autofocus on first input

---

site/src/app/components/pass-sport-footer/PassSportFooter.tsx
site/src/app/components/pass-sport-navigation/PassSportNavigationPro.tsx
site/src/app/components/pass-sport-navigation/PassSportNavigationStandard.tsx
site/src/app/v2/plan-du-site/page.tsx
site/src/app/v2/pro/plan-du-site/page.tsx

Removed aria-label from "Je suis une structure partenaire" and "Je suis un particulier" from every where

[Frontend] Removed unecessary aria-label

---

site/src/app/constants/footer-brand-top.tsx

- https://www.notion.so/Audit-avec-tickets-notion-526ecd6d84764c0c84844c2e41071fe2?p=10cd86210f7a804a8f7dc6df69540da6&pm=s

[Frontend] Wording fix

---

site/src/app/v2/test-eligibilite/components/eligibility-test-forms/EligibilityTestForms.tsx

- fix : le 3eme fieldset qui etait vide
- fix: la reponse negative n'est plus dans le dernier fieldset

[fix] fieldset number

---

site/src/app/v2/trouver-un-club/components/club-list-view/more-clubs-button/MoreClubsButton.tsx

[ticket](https://www.notion.so/R-sultat-de-la-liste-1fee5fef1bbc4b1a8adc3f3d3401d96a?pvs=4)

[Accessibility] revert find more club button

---

site/src/app/constants/footer-brand-top.tsx

- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=10cd86210f7a8018ba58e4a4426e7c0a&pm=s

[Frontend] Header logo updated

---

site/src/app/hooks/useLeafletAccessibility.tsx
site/src/app/v2/trouver-un-club/[club-name]/components/map/Map.tsx
site/src/app/v2/trouver-un-club/components/clubs-map/ClubsMap.tsx
site/src/app/v2/trouver-un-club/components/clubs-map/MapEventHandler.tsx
site/src/app/v2/trouver-un-club/components/clubs-map/MapZoomHandler.tsx

[ticket](https://www.notion.so/Texte-non-traduit-sur-le-marqueur-1d0a5df73112459099935cb3d79d0e81?pvs=4)
[ticket](https://www.notion.so/Boutons-de-la-carte-bb8e3f6ef52e4f0793b8bf74c7230b0d?pvs=4)

translate parts of leaflet map

---

site/instrumentation.ts

Suggestion as we're now a 184k events/day

chore(sentry): reduce tracesSampleRate

---

site/middleware.ts

Revert CSP removal, images from FAQ not working anymore for the time being

Revert "remove useless csp"

---

site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumbPro.tsx
site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumbStandard.tsx
site/src/app/components/pass-sport-footer/PassSportFooter.tsx
site/src/app/v2/accessibilite/page.tsx
site/src/app/v2/accessibilite/style.module.scss

⬆️ 
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=59367a6df5784a029ab04c0d651ce909&pm=s

[Frontend] Accessibility declaration page

---

site/src/app/v2/accessibilite/page.tsx

Updated accessibility declaration page

[Frontend] Accessibility page updated

---

site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx

[Frontend] Contact form, added one reason for boursiers

---

site/src/app/v2/code/scan/components/QrCodeCard/QrCodeCard.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/AahMsaForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/YoungMsaForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/common-inputs/CommonInputs.tsx

🆙 
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=11ad86210f7a80b5a05cf4b08b650b11&pm=s

[Frontend] Handled empty codes & fixed autofocus on forms

---

site/src/app/v2/test-eligibilite/components/step-one-form/StepOneForm.tsx

⬆️ 
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=11cd86210f7a809ab2e3d9b7a9da2ce7&pm=s

[Frontend] Forms wording update

---

site/global.d.ts
site/src/app/components/pass-sport-footer/PassSportFooter.tsx
site/src/app/components/tarte-au-citron/tarte-au-citron.tsx
site/src/app/globals.scss
site/src/app/hooks/accessibility/use-enhance-cookie-manager-accessibility.ts
site/src/app/tac-dsfr.scss
site/src/app/v2/accueil/components/video/styles.module.scss

[Tarteaucitron] Redesign to fit DSFR theme

---

site/src/app/components/social-media-panel/styles.module.scss
site/src/app/v2/pro/accueil/page.tsx
site/src/app/v2/pro/accueil/styles.module.scss

- Homepage user version, social media links component spacing missing
- Homepage pro version, background-color not applied correctly
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=121d86210f7a80438a69fa838cce88ee&pm=s
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=121d86210f7a80a7b81ef9573854f91b&pm=s

[Frontend] UI fixes

---

site/pages/api/contact.ts
site/utils/string.spec.ts
site/utils/string.ts

Add "est-drajes" segment to crisp whenever "DRAJES" (case insensitive) is found within the message (exact word, not within a word etc.)
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=121d86210f7a8061abd5dd67b6101daf&pm=s

[Backend] DRAJES Segment

---

data/2024/experimentation/experience-1/1_ditp_extract_columns_from_lm_hard_bounce_campaign.ipynb
data/2024/experimentation/experience-3/3_ditp-analysis.ipynb

Notebooks updated for DITP experience 1 and 3
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=123d86210f7a807baf47cd6eaba32095&pm=s

[Jupyter] DITP notebooks updated for experience 1 and 3

---

data/2024/experimentation/experience-1/1_ditp_extract_columns_from_lm_hard_bounce_campaign.ipynb
data/2024/experimentation/experience-2/2_ditp_consolidation_and_update.ipynb
data/2024/experimentation/experience-2/3_ditp-maquettes-analysis.ipynb
data/2024/experimentation/experience-2/check_analysis_file.ipynb
data/2024/experimentation/experience-3/3_ditp-analysis.ipynb

- Parent files were not matching the correct objet/mail type (control/test)
- Added another notebook to check length of each generated file for DITP

[Juypter] DITP notebooks experience 2 fixes

---

site/src/app/components/mission-cards/MissionCards.tsx

[Frontend] SPE - typo fix

---

site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumbStandard.tsx
site/src/app/components/pass-sport-footer/PassSportFooter.tsx
site/src/app/v2/reglement-du-jeu-concours-numero-pass-sport-decathlon/page.tsx
site/src/app/v2/reglement-du-jeu-concours-numero-pass-sport-decathlon/style.module.scss

- Added page for decathlon concours
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=13cd86210f7a8004ad99ea9bbfa5e652&pm=s

[Frontend] Jeu concours decathlon

---

data/2024/experimentation/experience-2/2_ditp_consolidation_and_update.ipynb

[Jupyter] Added small filter (people opened)

---

site/src/app/v2/trouver-un-club/components/club-finder/ClubFinder.tsx
site/src/app/v2/trouver-un-club/components/club-finder/helpers/get-additional-cities.helper.spec.ts
site/src/app/v2/trouver-un-club/components/club-finder/helpers/get-additional-cities.helper.ts

See ticket for more details
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=144d86210f7a804faafad6c28a97ca34&pm=s

[Frontend] Temporary workaround for lost clubs

---

site/src/app/globals.scss
site/src/app/layout.tsx

[Frontend] Leaflet marker fix - Reverted leaflet minified script

---

site/src/app/v2/reglement-du-jeu-concours-numero-pass-sport-decathlon/page.tsx

[Frontend] Concours decathlon typo fix

---

site/package-lock.json
site/package.json
site/scripts/send-in-mass.mjs

Script ran on the 9th december 2024
Context: We needed to send a message to the remaining conversations that were
unresolved, unassigned, not from LSM, DRAJES, DSRGPD
in order to have fresh & relevant replies from people in need
Once the message is sent, the conversation is resolved, and any time the conversation is resumed,
the conversation's state rolls back to "unresolved"
Te CRISP API is called thousands of times, it is a very unstable API so the script had to be re-ran multiple times

[Backend] Send in mass - CRISP script

---

.gitignore
site/src/app/v2/accueil/components/acronymes/Acronymes.tsx
site/src/app/v2/api/eligibility-test/confirm/route.ts
site/src/app/v2/test-eligibilite-base/helpers/helpers.ts
site/src/app/v2/test-eligibilite/components/allowance-step/AllowanceStep.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/CrousForm.tsx
site/src/app/v2/test-eligibilite/helpers/helper.spec.ts

- Updated /confirm endpoint to support BFC boursiers
- Updated form
- Removed "CROUS" and replaced it with "Boursier de l'enseignement supérieur"
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=157d86210f7a80b28a7dfc57233b6dd7&pm=s

[Frontend] Boursiers sanitaires et sociaux BFC tweaks

---

site/package.json
site/scripts/send-in-mass-march-2025.mjs

- Implementation of a script to fetch conversation, send message in it, resolve it for all the conversations that are unassigned & unresolved
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=1b2d86210f7a802c82cedfe9ad30f7e7&pm=s

[Backend] CRISP Script to send message in mass

---

site/package-lock.json
site/package.json

CVE -> https://nextjs.org/blog/cve-2025-29927

[Next] NextJS upgrade (CVE)

---

.gitignore
site/src/app/v2/accueil/components/video/styles.module.scss

⬆️ 
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=1d1d86210f7a80898fd4d8316e92a8d1&pm=s

[Frontend] Homepage - Vimeo width/height fixed

---

site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/components/styles.module.scss

⬆️  
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=1d1d86210f7a80898fd4d8316e92a8d1&pm=s

[Frontend] Pro version - Video dimension fixes

---

site/package-lock.json
site/package.json
site/src/app/components/pass-sport-footer/PassSportFooter.tsx
site/src/app/components/pass-sport-navigation/navigation.tsx
site/src/app/v2/plan-du-site/page.tsx
site/src/app/v2/pro/plan-du-site/page.tsx

- Removed tableau de bord links
- Upgraded nextjs to latest 14
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=1f3d86210f7a80caa3faf2e394a28ab6&pm=s

[Frontend] Removed tableau de bord links

---

site/src/app/v2/accueil/components/callout/callouts.messages.ts

[Frontend] Homepage - Updated stats

---

site/src/app/components/pass-sport-footer/PassSportFooter.tsx
site/src/app/v2/pro/accueil/page.tsx
site/src/app/v2/pro/ressources/page.tsx
site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/page.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/components/about.tsx

- Updated the name of the Ministre
- Removed the partners section

[Frontend] Ministre updated et partners removal

---

site/src/app/v2/accueil/page.tsx
site/src/app/v2/tout-savoir-sur-le-pass-sport/page.tsx

- Removed video from homepage
- Replaced "Tout savoir sur le pass Sport" content by "En cours de construction"

[Frontend] Site updates

---

site/src/app/components/pass-sport-footer/PassSportFooter.tsx
site/src/app/components/pass-sport-navigation/PassSportNavigationPro.tsx
site/src/app/components/pass-sport-navigation/PassSportNavigationStandard.tsx
site/src/app/components/pass-sport-navigation/navigation.tsx
site/src/app/constants/urls.tsx
site/src/app/manifest.ts
site/src/app/v2/accueil/components/hero-panel/HeroPanel.tsx
site/src/app/v2/plan-du-site/page.tsx
site/src/app/v2/pro/plan-du-site/page.tsx
site/utils/date.ts

- Chatbot links (on hold for now)
- Wordings update header + hero panel

[Frontend] Wordings update + chatbot

---

site/src/app/v2/accueil/components/find-club-card/FindClubCard.tsx

[Frontend] Homepage - club count rollback

---

site/src/app/Matomo.tsx

- Campaigns are not being tracked (mtm_campaign), so trying to setCustomUrl only if we are from the sensitive /v2/code/scan page

[Frontend] Matomo - Tracking issue

---

site/src/app/v2/test-eligibilite/page.tsx

[Frontend] Disable eligibility page

---

site/src/app/v2/une-question/page.tsx

[Frontend] Une question page - removed eligibility banner

---

site/src/app/v2/pro/une-question/page.tsx
site/src/app/v2/une-question/components/ContactSection/ContactSection.tsx
site/src/app/v2/une-question/components/ContentSection/ContentSection.tsx
site/src/app/v2/une-question/components/ContentSection/styles.module.scss
site/src/app/v2/une-question/page.tsx

[Frontend] FAQ Activation (Pro + User)

---

site/src/app/components/skip-links-wrapper/SkipLinksWrapper.tsx
site/src/app/v2/accueil/page.tsx
site/src/app/v2/accueil/styles.module.scss
site/src/app/v2/jeunes-et-parents/page.tsx

[Frontend] Skip link fixes & Homepage mobile ui fix

---

site/pages/api/contact.ts
site/utils/string.spec.ts
site/utils/string.ts

- Added support for automatic segment "est-lsm" when message contains "LSMUSC2025"

[Backend] LSM Segment support

---

site/pages/api/contact.ts
site/src/app/v2/api/eligibility-test/confirm/route.ts
site/src/app/v2/api/eligibility-test/search/route.ts
site/src/app/v2/test-eligibilite/components/step-one-form/StepOneForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/AahCafForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/AahMsaForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/CrousForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/YoungCafForm.tsx
site/src/app/v2/test-eligibilite/components/step-two-forms/YoungMsaForm.tsx
site/src/app/v2/une-question/page.tsx
site/types/EligibilityTest.ts

- Added allowance name to the cookie support
- Updated wordings to be human readable

[Frontend/Backend] feat: formatted notes, added allowance name and rewordings

---

site/utils/eligibility-test.spec.ts
site/utils/eligibility-test.ts

[Frontend] Display aeeh link for 18-19 years old

---

site/src/app/components/simplified-eligibility-test/SimplifiedEligibilityTest.tsx
site/src/app/v2/jeunes-et-parents/components/ContactAeehSection.tsx
site/src/app/v2/test-eligibilite/components/allowance-step/AllowanceStep.tsx
site/src/app/v2/test-eligibilite/components/verdict-panel/VerdictPanel.tsx

- Simplified eligibility test (simulator), 
- Eligibility conditions displayed instead of link in case of error
- Link to Demarches simplifiees in case of success for AEEH
- Eligibility test (form to obtain code)
- For AEEH, display more information in case of success

[Frontend] feat: both forms wordings update and links updated

---

site/src/app/v2/structures/components/AccordionsBecomePartner.tsx
site/src/app/v2/structures/components/AccordionsTools.tsx

[Frontend] Page Structures sportives - Updated faq articles title

---

site/src/app/v2/structures/components/AccordionsBecomePartner.tsx

[Frontend] chore: become partner article update

---

site/src/app/components/je-donne-mon-avis-btn/JeDonneMonAvisBtn.tsx

⬆️ 
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=280d86210f7a8008b5afd7a074b0caa0&pm=s

[Frontend] chore: updated jedonnemonavis ids
