- site/src/app/components/pass-sport-footer/PassSportFooter.tsx
Petite PR suite à un feedback de Perrine sur le footer
- Pas de liens ouvrant une nouvelle fenêtre pour les liens internes
> [Footer] Mis à jour de l'UI pour les liens internes

- site/src/app/components/pass-sport-breadcrumb/styles.module.scss
> [Frontend] Breadcrumb UI fix found in club page

- site/src/app/components/pass-sport-navigation/navigation.tsx
Tout savoir sur le pass'sport was not clickable on mobile
(Removed aria-hidden and only used text, because it is not necessary)
https://github.com/betagouv/pass-sport/assets/1215376/f6c60fa7-b1b9-468f-81a1-e11842fc6ff5
https://www.notion.so/Page-Tout-savoir-sur-le-Pass-Sport-cdb34d560f9b415e8093c35f4dc7ec94?d=0d392d8d5e6c429aba17672a34974a03
> [Frontend] Pass Sport navigation on mobile

- site/components/PageHeader/PageHeader.tsx
- site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumb.tsx
- site/src/app/components/pass-sport-footer/PassSportFooter.tsx
- site/src/app/v2/mentions-legales/page.tsx
- site/src/app/v2/mentions-legales/style.module.scss
- site/src/app/v2/politique-de-confidentialite/page.tsx
- site/src/app/v2/politique-de-confidentialite/style.module.scss
~~Draft, awaiting for confirmation of the page's content from David~~
Content updated
Implementation of pages:
- Données personnelles
- Mentions légales
- "Mentions légales" content OK? (It is a copy/paste from https://pass.sports.gouv.fr/mentions-legales/, but excluding the "Enquete" section)
- "Données personnelles" content OK? (The numbering seems OFF)
> [Frontend] "Données personnelles" + "Mentions légales" pages

- site/src/app/v2/une-question/components/ContentSection/ContentSection.tsx
- site/src/app/v2/une-question/server-agent.ts
Temporary fix, hide categories/articles when being hit by rate limit from CRISP API (we shouldn't be rate limited with our token)
This caused the page to crash
> [Backend][Frontend] Handle rate limit error on FAQ

- site/package-lock.json
- site/package.json
- site/utils/faq.ts
Added in memory caching for API calls made to CRISP for getting articles/categories
Use of the library [node-cache](https://www.npmjs.com/package/node-cache)
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=c317f92d7d5b4e1eaf2affccb958b58e&pm=s
> [Backend] In memory caching for FAQ Crisp API calls

- site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumbPro.tsx
- site/src/app/components/pass-sport-navigation/navigation.tsx
- site/src/app/v2/pro/tout-savoir-sur-le-pass-sport/page.tsx
- After the re-introduction of the menu spacer item in the navigation, the "Tout savoir sur le pass sport" was no longer clickable again on mobile. The fix was to put the text alongside the div containing the styling for the spacer item
- Fix tout savoir sur le pass sport social media panel links UI (it used to not take the whole width)
- Fix on the Home page link in the pro version
> [Frontend] Navigation fix + tout-savoir-sur-le-pass-sport UI fix + Breadcrumb fix

- site/src/app/components/pass-sport-navigation/PassSportNavigationPro.tsx
- site/src/app/components/pass-sport-navigation/PassSportNavigationStandard.tsx
- site/src/app/components/pass-sport-navigation/navigation.tsx
- site/src/app/components/pass-sport-navigation/styles.module.scss
- Added Tableau de bord external link in user/pro version
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=320a1b9091d341f084bb8a69b873c0d2&pm=s
> [Frontend] Header navigation added tableau de bord

- site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumbStandard.tsx
- site/src/app/components/pass-sport-footer/PassSportFooter.tsx
- site/src/app/components/pass-sport-navigation/navigation.tsx
- site/src/app/v2/accueil/components/find-club-card/FindClubCard.tsx
- site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx
Update the following wording in header + footer + breadcrumb
- "Trouver un club partenaire" => "Trouver une structure partenaire"
- "Carte des structures partenaires" remains unchanged
https://www.notion.so/Footer-Support-des-liens-en-version-pro-et-utilisateur-mettre-jour-le-niveau-de-conformit-acc-d301326c7de74c4ab96561c920c396a4
> [Frontend] Updated typo for user/pro version in footer+header+breadcrumb

- site/src/app/v2/pro/une-question/page.tsx
- site/src/app/v2/pro/une-question/styles.module.scss
- site/src/app/v2/une-question/components/ContactForm/ContactForm.tsx
- site/src/app/v2/une-question/components/ContentSection/ContentSection.tsx
- site/src/app/v2/une-question/server-agent.ts
- site/utils/faq.ts
Staging environment for Paula & Julien to check FAQ articles/categories live without CACHE
Various changes:
- Selecting an article is now displaying ONE article fully expanded and not the whole list expanded
- Added support to link FAQ to one given article (articleId query parameter)
- Implemented pro version of the FAQ
- Use of category identifiers (Pro & User version) to get matching categories & articles depending on the page (pro or user version)
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=baf5f0d00aac40479a48c1f997faf980&pm=s
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=4be0f00b105c4363a89c3ec91fa70d33&pm=s
- https://www.notion.so/En-tant-que-structure-partenaire-je-souhaite-acc-der-la-F …
> [Frontend] FAQ - Various changes + testing environment for Paula & David

- site/src/app/components/pass-sport-footer/PassSportFooter.tsx
Link gouvernement.fr -> info.gouv.fr
The property **domains** is not documented in https://components.react-dsfr.codegouv.studio/?path=/docs/components-footer--default
I had to go into the DSFR's source code to know the existence of this props
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=0621e252aa1d4263b0d5e4be8ce00361&pm=s
> [Frontend] Footer - domains updated

- site/components/PageHeader/PageHeader.tsx
- site/src/app/v2/une-question/components/ContentSection/ContentSection.tsx
- Sur la page détaillant un article, lorsque ce l’on clique dessus, il ne devrait pas y avoir de changement de page. (cela empêche de copier/coller du texte provenant de l’article)
- Lorsque l’on clique sur un article, le scroll devrait s’arrêter au niveau de l’article
- Lorsque l’on clique sur le bouton “Retour” d’un article, le scroll ne devrait pas aller tout en haut de la page mais plutôt au niveau du PageHeader
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=164d489e35fb4b3490f2e20100bcdf8a&pm=s
> [Frontend] FAQ UX Improvements

- site/src/app/Matomo.tsx
In QR recap page, replace code with 24-xxxx-xxxx before pushing event to matomo
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=f372de3c869d420889a998d652114d70&pm=s
> [Frontend] Hide code in url before pushing event to matomo

- site/src/app/v2/api/eligibility-test/confirm/route.ts
pas sur que ce soit la raison du bug "buildQRCodeUrl() Cannot destructure property 'nom' of 'e[0]' as it is undefined."
mais ca peut.
> fix / handle bad status response from LCA /confirm

- site/src/app/v2/code/scan/[encrypted]/page.tsx
- On Recap QR code page, when displaying firstname and last name, replace double quotes with single quote
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=c24e66d3991d4041bde0c8ab9c4ef067&pm=s
> [Frontend] QR Code page recap - Replace double quotes with single quote

- site/src/app/components/pass-sport-navigation/PassSportNavigationPro.tsx
- site/src/app/components/pass-sport-navigation/PassSportNavigationStandard.tsx
In the PassSportNavigation pro/user version, did the following
- "Je suis un particulier" from button to link
- "Je suis une structure partenaire" from button to link
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=2aa60021b949421789054f5029f129e6&pm=s
> [Frontend] header navigation, transformed buttons to links

- site/src/app/constants/search-query-params.ts
- site/src/app/hooks/use-append-query-string.tsx
- site/src/app/hooks/use-remove-query-string.tsx
- site/src/app/v2/pro/trouver-un-club/page.tsx
- site/src/app/v2/trouver-un-club/agent.ts
- site/src/app/v2/trouver-un-club/components/club-filters/ClubFilters.tsx
- site/src/app/v2/trouver-un-club/components/club-filters/activity-filter/ActivityFilter.tsx
- site/src/app/v2/trouver-un-club/components/club-filters/city-filter/CityFilter.tsx
- site/src/app/v2/trouver-un-club/components/club-filters/handicap-filter/HandicapFilter.tsx
- site/src/app/v2/trouver-un-club/components/club-filters/region-filter/RegionFilter.tsx
- site/src/app/v2/trouver-un-club/components/club-filters/styles.module.scss
- site/src/app/v2/trouver-un-club/components/club-finder/ClubFinder.tsx
- site/src/app/v2/trouver-un-club/components/search/Search.tsx
- site/src/app/v2/trouver-un-club/page.tsx
- site/utils/string.ts
- Added persistence for all filters except the pagination
- Turned handicap filter into toggle switch
- Added bug fixes when searching for activities & club names containing single quotes (escape single quote before making API calls)
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=e3dd8cdd2e484d1eabb2d222b9d363d3&pm=s
~~QA my own work~~
> [Frontend] Persist search in find a club page (added query parameters for all filters)

- site/components/PageHeader/styles.module.scss
- site/src/app/components/pass-sport-breadcrumb/styles.module.scss
- site/src/app/components/social-media-panel/styles.module.scss
Background color updated for:
- Breadcrumb, 
- Page header,
- Social media links panel
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=c728fb21096041819f07954f2d7d9f63&pm=s
> [Frontend] Background color updated

- site/src/app/Matomo.tsx
the package "@socialgouv/matomo-next" automatically tracks page view via the init function via a trackpageview call. In addition, this automatic tracking is partially disfunctional on next 14. 
=> this fix disables completely the automatic tracking from this package. 
the operational remaining tracking is the tracking mechanism written manually in the Matomo.tsx file.
> fix / disable automatic tracking for matomo

- site/src/app/v2/plan-du-site/style.module.scss
Before ->
After ->
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=99e1b296a1544b45b3f1f87354171dfb&pm=s
> [Frontend] Plan du site, background color updated

- site/src/app/services/__snapshots__/eligibility-test.spec.ts.snap
- site/src/app/services/eligibility-test.spec.ts
- site/src/app/services/eligibility-test.ts
- site/tests/api/eligibility-test/search/__snapshots__/route.test.ts.snap
- site/tests/api/eligibility-test/search/route.test.ts
[ticket](https://www.notion.so/Supprimer-le-double-appel-l-api-LCA-97a201d7f5c24c3fa38733bf837654e0?pvs=4)
[review app](https://pass-sport-staging-pr177.osc-secnum-fr1.scalingo.io)
> remove calls to obsolete lca api routes

- site/src/app/components/pass-sport-breadcrumb/styles.module.scss
⬆️ 
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=8947198284c245c7ad0e6d8c17be78e8&pm=s
> [Frontend] Breadcrumb - last part of breadcrumb (text) color updated

- site/package-lock.json
- site/package.json
- site/src/app/v2/trouver-un-club/[club-name]/components/clubDetails/ClubDetails.tsx
- site/src/app/v2/trouver-un-club/[club-name]/components/medicalCertificatPanel/MedicalCertificatePanel.tsx
- site/src/app/v2/trouver-un-club/[club-name]/hooks/use-get-map-url.ts
- site/src/app/v2/trouver-un-club/[club-name]/style.module.scss
- site/types/Club.ts
- Go to itinerary implementation on club details page
- Matomo tracking on itinerary link clicks
- Fixed existing semantic HTML bug (paragraph cannot be descendant of paragraph error) in MedicalCertificatePanel
If user gives permission to get its location, we use the directions in googlemaps, otherwise we just search for a specific place
If the club has the geocoordinates we take them, otherwise we take its address, if it has none of these, we don't display the itinerary URL
https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=0e281b3961994df4880e362ae0c9bc96&pm=s
> [Frontend] Itinerary implementation & various fixes

- .github/workflows/nginx-test.yml
docker-compose v1 has been deprecated [here](https://github.com/actions/runner-images/issues/9692)
The fix is to use the v2 command that is to say **docker compose**
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=0967d742104d47e08490b4554957f6ab&pm=s
> [CI] CI fixes due to ubuntu-latest image runner migration 

- site/src/app/Matomo.tsx
In the setCustomUrl callback, we handle the hashtag that appears on the QR page code recap. For some reason Matomo is sometimes pushing the URL with the hashtag even though this option has been disabled by the beta.gouv team
- https://www.notion.so/65db4ac9850e4b8c9cab4954ad154035?p=9a9e6bd033d2487c849b85773aeeb441&pm=c
> [Frontend][Matomo] Safeguard hashtag matmom bugfix

- site/src/app/v2/accueil/page.messages.tsx
- site/src/app/v2/code/scan/components/QrCodeCard/QrCodeCard.tsx
- site/src/app/v2/trouver-un-club/[club-name]/components/clubDetails/ClubDetails.tsx
- Homepage: One liner for text (Couldn't find any way to solve it, adding spaces doesn't work)
- QR recap page: When clicking on the copy button, an alert is now displayed and is closeable
- Club details page, use address HTML element
- https://www.notion.so/Audit-avec-tickets-notion-526ecd6d84764c0c84844c2e41071fe2?p=3cafd73b31324e7ea0a4ceaa33ca5669&pm=s
- https://www.notion.so/Audit-avec-tickets-notion-526ecd6d84764c0c84844c2e41071fe2?p=8b45a6401726480797554b91229df52d&pm=s
- https://www.notion.so/Audit-avec-tickets-notion-526ecd6d84764c0c84844c2e41071fe2?p=3bb6c1be5b7b481e956f13e35a7a95bf&pm=s
> [Frontend] Homepage btn typo + qr copy code notif + club details <address>

- site/src/app/v2/pro/une-question/page.tsx
- site/src/app/v2/une-question/components/ContentSection/ContentSection.tsx
- site/src/app/v2/une-question/components/ContentSection/styles.module.scss
- site/src/app/v2/une-question/page.tsx
- The articleId query parameter can still be passed in and the matching accordion will be opened
- Example: <base-url>/v2/une-question?articleId=51975e40-7140-464e-ac93-ec611adec704 
- Redesign of the FAQ to avoid multiple navigations
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=103d86210f7a80108ca9d146ef3c886e&pm=s
> [Frontend] FAQ Redesign

- site/src/app/components/pass-sport-breadcrumb/PassSportBreadcrumbStandard.tsx
- site/src/app/components/pass-sport-footer/PassSportFooter.tsx
- site/src/app/v2/budget/page.tsx
- site/src/app/v2/budget/styles.module.scss
- site/src/app/v2/plan-du-site/page.tsx
- site/src/app/v2/pro/plan-du-site/page.tsx
- Budget page implementation + updated routing
- Added Budget link to footer
- Updated "Plan du site" pages to include Budget link (pro,user versions)
- https://www.notion.so/369742af22d9486097d69a9cc301c1c1?v=6e22fafc1b4f4333a53a8906eb814126&p=15fd86210f7a809292f2d35704dfa7ff&pm=s
> [Frontend] Budget page implementation

- site/src/app/v2/test-eligibilite-base/components/aeehStep/AeehStep.tsx
- site/src/app/v2/test-eligibilite-base/components/ageStep2/AgeStep2.tsx
- site/src/app/v2/test-eligibilite-base/components/allowancesStep/AllowancesStep.tsx
- site/src/app/v2/trouver-un-club/[club-name]/page.tsx
- site/src/app/v2/trouver-un-club/components/club-count/ClubCount.tsx
- site/src/app/v2/trouver-un-club/components/club-list-view/more-clubs-button/MoreClubsButton.tsx
- site/src/app/v2/trouver-un-club/page.tsx
- When finishing the eligibility test, the club count is wrong, should be 85 000 instead of 59 000
- Find a club page, 80 000 should be 85 000
- Eligibility test banner removed from find a club page + club details page on user version
> [Frontend] Eligiblity test - clubs count, eligibility test banner fixes

- site/src/app/components/simplified-eligibility-test/SimplifiedEligibilityTest.tsx
- site/src/app/v2/jeunes-et-parents/page.tsx
- Removed AEEH Contact form modal on page "Jeunes et parents"
- Updated simulator case for AEEH, it is no longer a link but a button that redirects to /v2/test-eliibilite
> [Frontend] Disable AEEH contact form modal on jeunes et parents & updated simulator 

- data/2025/aeeh/lm-reports-output-to-ds.ipynb
Process is the following
- Import the Link Mobility report file that contains the codes, emails, error message
- Take benefs that weren't delivered
- Match those benefs with data from production
- Output a CSV file with the folder id, email, code and link to Demarches Simplifiees
https://www.notion.so/Implementation-d-un-script-pour-extraire-les-b-n-ficiaires-non-delivr-s-des-vagues-AEEH-27dd86210f7a80728ea0cf59a9d44ddf
> [Backend] Link mobility report demarche simplifiees extraction
